### ISSUE TITLE
Fix or add warning about lowercased items in struct

### ISSUE THREAD

**Issue by C-Bouthoorn** [mitchellh/mapstructure#128]
```go
package main

import (
	"fmt"

	"github.com/mitchellh/mapstructure"
)

type myType struct {
	value int
}

func main() {
	myMap := map[string]interface{}{
		"value": 10,
	}

	var myVar myType

	err := mapstructure.Decode(myMap, &myVar)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", myVar)  // {value:0}
}
```

Apparently mapstructure failed to find the lowercased item in the struct. It took me quite a while to figure that out, so it would be nice if you could add a warning about it in the Readme file. Even better would be if you could add support for these lowercased items.

**Comment by mfridman** [comment]
This is likely by design, to keep it consistent with with how the standard lib behaves. Where each exported (uppercase) struct field is a member of the object and non-exported (lowercase) fields are not.

```go
type myType struct {
	Value string `mapstructure:"value"`
}
```

You don't need the tag `mapstructure` in this case because it's implied Value is value, but if you wanted a different name it's there.

**Comment by C-Bouthoorn** [comment]
Ah, I didn't know about the `mapstructure` tag. Thanks :smile:
