### ISSUE TITLE
Is this project no longer maintained? why? :(

### ISSUE THREAD

**Issue by inhere** [mitchellh/mapstructure#172]

**Comment by elimist3** [comment]
Mitchell too busy running his multi-national corporation now 😄

**Comment by mitchellh** [comment]
lol @elimist3 

I'm not a very good maintainer of this project because it falls into the trap of: it works really well for the use cases I (and our company) uses it for. I realize it has bugs though and I should be more attentive.

Its definitely being maintained, just very slowly. If anyone is interested in helping out I'd be open t it, but until then I do get to PRs eventually. Sorry!

**Comment by mfridman** [comment]
To echo @mitchellh, this project has a minimal API and works very well for its intended use-case. I've been using it since 2016 and quite confident with it in prod.

Many of the open issues are feature requests and how-to questions.

we could do a round of triage to see if there are any _real_ bugs to help reduce the number of open issues/PRs.. 

@inhere my experience to-date is that bugs in this project do, eventually, get fixed

**Comment by inhere** [comment]
@mfridman  ok, thank you.

**Comment by prochac** [comment]
May be closed, but any progress on it? At least with the triage to mark and serve the bugs with a priority?
