### ISSUE TITLE
Decode with options ?

### ISSUE THREAD

**Issue by gnoah1379** [mitchellh/mapstructure#243]
I think this way be better for flexibility.
```Go

type Option func(config *mapstructure.DecoderConfig)

func WithTag(tag string) Option {
	return func(config *mapstructure.DecoderConfig) {
		config.TagName = tag
	}
}
...
func Decode(input interface{}, output interface{}, opts ...Option) error {
	config := &mapstructure.DecoderConfig{
		Result:  output,
	}
	for _, opt := range opts {
		opt(config)
	}
	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}
	return decoder.Decode(input)
}

```

**Comment by cirelli94** [comment]
Functional options for friendly APIs!
Here an interesting talk from Dave Cheney about this https://youtu.be/24lFtGHWxAQ
I'd like to have this in mapstructure!

**Comment by mitchellh** [comment]
Yes, I would've preferred to do this and if I were writing this library from scratch today I'd probably do this. This is the correct modern approach that I simply wasn't aware of (and didn't exist) when I first wrote this library a decade ago. For now, I'd say we should NOT do this because it retains only one way to do things in the library, despite being antiquated.
